### ISSUE TITLE
隐藏或二次开发codeblitz右侧的AI研发助手

### ISSUE THREAD

**Issue by jues** [opensumi/codeblitz#107]
请问codeblitz右侧的AI研发助手是哪个布局管的？怎样隐藏？代码大概在哪个位置？getDefaultLayoutConfig返回的
{"top":{"modules":["@opensumi/ide-menu-bar"]},"action":{"modules":[""]},"left":{"modules":["@opensumi/ide-explorer","@opensumi/ide-search","@opensumi/ide-extension-manager","@opensumi/ide-scm"]},"main":{"modules":["@opensumi/ide-editor"]},"bottom":{"modules":["@opensumi/ide-output","@opensumi/ide-markers"]},"statusBar":{"modules":["@opensumi/ide-status-bar"]},"extra":{"modules":["breadcrumb-menu"]}}

看起来哪个都不像

启动codeblitz-sample的网页里没有研发助手，启动codeblitz项目就有

**Comment by bytemain** [comment]
![CleanShot 2024-07-30 at 17 13 42@2x](https://github.com/user-attachments/assets/6a9c7a59-df46-4d00-866f-a031483cf6f0)

如果使用了 DesignModule（codeblitz 项目中默认会引入）并且开启了 supportsChatAssistant 配置项就会启用
