### ISSUE TITLE
[Question] 如何默认收起左侧资源管理器

### ISSUE THREAD

**Issue by barry3406** [opensumi/codeblitz#113]
如何默认收起左侧资源管理器

**Comment by bytemain** [comment]
跟布局相关的都要拿到 IMainLayoutService 进行操作。

我们可以自定义一个 BrowserModule 来承载这些操作，推荐操作布局都要在 onDidRender 声明周期里，这个时候不需要担心某个布局是否初始化完成。

OpenSumi 中有 Contribution 的机制，只需要实现 MainLayoutContribution 的 onDidRender 方法就行。

然后将你的 Contribution 放到 BrowserModule 中，就能让 Codeblitz 加载这个 Contribution 了。

可以看下这个 PR:
- https://github.com/opensumi/codeblitz/pull/114
