### ISSUE TITLE
[Question] 会和stackblitz一样吗？特别是web container方面

### ISSUE THREAD

**Issue by chenshuichao** [opensumi/codeblitz#16]
**描述你的问题（Describe you question here）**

https://stackblitz.com，非常棒的体验！特别是web container技术。
可以说wasm，让真正的web ide变成可能。

**Comment by hacke2** [comment]
这次开源的是无需容器在浏览器的运行的 IDE 框架，类似于 stackblitz 提供的 IDE 产品一样，通过 codeblitz 可能做出类似于 stackblitz 一样的 IDE 产品，但是 stackblitz 除了 IDE 还有一块就是你说的 web container 的技术，这块本次没有开源，内部还在验证中，如果你有需要也可以直接使用 stackblitz 提供的 https://webcontainers.io/guides/quickstart 或者用 codesandbox 提供的 https://github.com/codesandbox/nodebox-runtime 来和 codeblitz 集成~
