### ISSUE TITLE
[BUG] 项目启动提示堆内存溢出错误导致启动失败

### ISSUE THREAD

**Issue by resetsix** [opensumi/codeblitz#20]
## 描述
CRA脚手架初始化后，按照官网教程`yarn add @codeblitzjs/ide-core`安装 IDE 组件。导入组件后启动报错，原因是堆内存溢出（电脑内存并没有占满）。

作为对比测试，我导入`Hello组件`能正常启动；而`App组件`使用的[官网完整示例](https://codeblitz.cloud.alipay.com/zh/docs/develop/api-docs/#%E4%BA%94%E5%AE%8C%E6%95%B4%E7%A4%BA%E4%BE%8B%E5%8F%82%E8%80%83)。App组件启动（命令`yarn start`）就堆内存溢出。根据gpt提示使用`yarn start --max-old-space-size=4096`也还是报相同的错。

![图片](https://github.com/opensumi/codeblitz/assets/85431995/afafe258-6b00-4d3c-8643-7937bdf02dba)

![图片](https://github.com/opensumi/codeblitz/assets/85431995/cae302b3-52d1-4de3-b2c8-e637e0f914d3)

## 依赖版本

![图片](https://github.com/opensumi/codeblitz/assets/85431995/01b23c6b-5101-4e36-862b-5aa72a7fe0bd)

## 复现代码
https://github.com/resetsix/CodeBlitz

**Comment by AhkunTa** [comment]
内存溢出问题  应该和项目没关系 可以在扩大下 内存 --max-old-space-size=8192 试下 
除此之外  示例项目还有部分配置项需要改动 
- 需将react 改动至16 版本  https://github.com/opensumi/core/issues/861
- .env 添加配置项 GENERATE_SOURCEMAP=false
- 部分代码同步修改

<img width="749" alt="截屏2023-10-07 18 47 17" src="https://github.com/opensumi/codeblitz/assets/31676999/2f785aff-f3e3-4c11-98ff-14e494d6c4af">



以下是具体的package.json
```json
{
  "name": "ide",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@codeblitzjs/ide-core": "^1.0.4",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.53",
    "@types/react": "^18.2.22",
    "@types/react-dom": "^18.2.7",
    "node-gyp": "^9.4.0",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "resolutions": {
    "electron": "^18.3.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
