### ISSUE TITLE
期望codeblitz支持ide-notebook

### ISSUE THREAD

**Issue by xinrulianhua** [opensumi/codeblitz#247]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- Codeblitz Version: [e.g. 1.0.0]

**Comment by hacke2** [comment]
这个模块可以集成，你能提个 PR 吗？

**Comment by xinrulianhua** [comment]
> **描述你的问题（Describe the bug）**
> 
> **复现路径（To Reproduce）**
> 
> **预期表现（Expected behavior）**
> 
> **环境信息（Environment）**
> 
> * OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
> * Browser: [e.g. chrome, safari, electron]
> * Codeblitz Version: [e.g. 1.0.0]
