### ISSUE TITLE
请问只支持github吗

### ISSUE THREAD

**Issue by DengJianShen** [opensumi/codeblitz#25]
gitee可不可以

**Comment by AhkunTa** [comment]
内部gitee代码服务已经集成 这个月会将 内部 code-api 模块开放出来 

https://codeblitz.cloud.alipay.com/gitee/opensumi/codeblitz

**Comment by DengJianShen** [comment]
> 内部gitee代码服务已经集成 这个月会将 内部 code-api 模块开放出来
> 
> https://codeblitz.cloud.alipay.com/gitee/opensumi/codeblitz

gitlab会支持吗

**Comment by DengJianShen** [comment]
> 内部gitee代码服务已经集成 这个月会将 内部 code-api 模块开放出来
> 
> https://codeblitz.cloud.alipay.com/gitee/opensumi/codeblitz

企业级的gitlab要怎么使用，我看到有相关代码但不知道该如何使用
```javascript
  [CodePlatform.gitlab]: {
    platform: CodePlatform.gitlab,
    hostname: ['gitlab.cn'],
    origin: 'https://gitlab.cn',
    endpoint: 'https://gitlab.cn',
    brand: 'GitLab',
    line: {
      parse(hash: string) {
        let matched: RegExpMatchArray | null = null;
        matched = hash.match(/^#L(\d+)(?:-(\d+))?$/);
        if (matched) {
          return [+matched[1], +(matched[2] || matched[1])];
        }
        return null;
      },
      format([startLineNumber, endLineNumber]) {
        if (startLineNumber === endLineNumber) {
          return `#L${startLineNumber}`;
        }
        return `#L${startLineNumber}-${endLineNumber}`;
      },
    },
  },
```

**Comment by DengJianShen** [comment]
> 内部gitee代码服务已经集成 这个月会将 内部 code-api 模块开放出来
> 
> https://codeblitz.cloud.alipay.com/gitee/opensumi/codeblitz

我做了一些调整 但还是显示github
![image](https://github.com/opensumi/codeblitz/assets/19514719/6a60f7ba-64af-4a5e-a1bc-8836e0d130f2)

![image](https://github.com/opensumi/codeblitz/assets/19514719/bd5f8826-3b2f-4f72-98f0-483a53fc9700)
