### ISSUE TITLE
请问gitlab怎么使用，做了一些修改还是显示的github

### ISSUE THREAD

**Issue by DengJianShen** [opensumi/codeblitz#26]
![image](https://github.com/opensumi/codeblitz/assets/19514719/bd5f8826-3b2f-4f72-98f0-483a53fc9700)

![image](https://github.com/opensumi/codeblitz/assets/19514719/6a60f7ba-64af-4a5e-a1bc-8836e0d130f2)

**Comment by AhkunTa** [comment]
参考  https://github.com/opensumi/codeblitz/pull/28
