### ISSUE TITLE
[Question] 协作分支里使用的 collaboration 插件是如何实现的

### ISSUE THREAD

**Issue by DabenW** [opensumi/codeblitz#32]
**协作分支里使用的 collaboration 0.0.2 这个插件是如何实现的，目前文档说明较少**

目前我们尝试验证在招聘考试系统接入 codeblitz，依赖到其中的协作模块。尝试目前的 demo 发现只实现了部分，并且像 ApplyOperation 、ApplySelection 等逻辑是在 collaboration 这个插件内的。想了解下这个插件的具体实现，以及可以添加些协作模块开发的使用文档

```ts
export enum LIVE_COMMAND {
  Reconnect = 'collaboration.reconnect',
  Initialize = 'collaboration.initialize',
  Initialized = 'collaboration.initialized',
  SendOperation = 'collaboration.sendOperation',
  ApplyOperation = 'collaboration.applyOperation',
  SendSelection = 'collaboration.sendSelection',
  ApplySelection = 'collaboration.applySelection',
  Join = 'collaboration.join',
  Leave = 'collaboration.level',
  SyncState = 'collaboration.syncState',
}
```
比如像框架中上面这些命令，有部分是注册在 plugin.ts 里的，有部分似乎是在 collaboration extension 里的

**Comment by AhkunTa** [comment]
插件侧主要是  参考 https://github.com/Operational-Transformation/ot.js 自实现了一套 OT 交互

目前正在走对外流程 下周会将 `collaboration` 插件 开源出来

**Comment by DabenW** [comment]
> 插件侧主要是 参考 https://github.com/Operational-Transformation/ot.js 自实现了一套 OT 交互
> 
> 目前正在走对外流程 下周会将 `collaboration` 插件 开源出来

@AhkunTa 这个有进展了嘛，目前我们的项目接入这一块也比较阻塞。demo 的 collaboration 插件似乎每次都会创建个 code 文件，我们可能得在此基础上做些修改

**Comment by AhkunTa** [comment]
> > 插件侧主要是 参考 https://github.com/Operational-Transformation/ot.js 自实现了一套 OT 交互
> > 目前正在走对外流程 下周会将 `collaboration` 插件 开源出来
> 
> @AhkunTa 这个有进展了嘛，目前我们的项目接入这一块也比较阻塞。demo 的 collaboration 插件似乎每次都会创建个 code 文件，我们可能得在此基础上做些修改

https://github.com/opensumi/codeblitz-sample/pull/4
