### ISSUE TITLE
[Question]  启动问题

### ISSUE THREAD

**Issue by gaoshengqing21** [opensumi/codeblitz#34]
您好，我想知道这个项目对应的python版本是多少呢
Directory: D:\gitClone\codeblitz\node_modules\nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@18.18.0 | win32 | x64
gyp info find Python using Python version 3.11.5 found at "D:\python\python.exe"
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn UNKNOWN，
我在yarn安装时一直提升该报错呢

**Comment by AhkunTa** [comment]
codeblitz 内开发环境和opensumi一样 参考 https://opensumi.com/zh/docs/develop/how-to-contribute

**Comment by gaoshengqing21** [comment]
您好，我这边是一个前端，不太理解 opensumi/core 与 opensumi/codeblitz的区别是什么呢？

**Comment by hacke2** [comment]
看一下这篇文章 https://mp.weixin.qq.com/s/Rkhqy-O6ZVPuHRw2jNsqCg
