### ISSUE TITLE
[BUG] 无法安装包

### ISSUE THREAD

**Issue by Leslie2014** [opensumi/codeblitz#39]
**描述你的问题（Describe the bug）**

包安装不下来
<img width="1149" alt="image" src="https://github.com/opensumi/codeblitz/assets/5417213/e7c952f2-a6c6-46c2-862a-ea403e11dc0d">

**复现路径（To Reproduce）**

python 3.12.0 版本会出现这个问题。
根据官网描述 3.12.0 会移除 distutils 模块。而我们包安装的时候需要依赖这个包编译。

<img width="889" alt="image" src="https://github.com/opensumi/codeblitz/assets/5417213/ce6cb47d-584a-4ff3-b4a9-fa9432dece16">

**预期表现（Expected behavior）**

能够正常安装。

**环境信息（Environment）**

- OS: macOS 14.0
- Codeblitz Version: latest

**Comment by bytemain** [comment]
先降级到 3.10 吧。
或者集成方先更新 [node-gyp 10.0.0](https://github.com/nodejs/node-gyp/releases/tag/v10.0.0) ，支持了 3.12
