### ISSUE TITLE
[Question] 请问支持gitee的仓库吗

### ISSUE THREAD

**Issue by DengJianShen** [opensumi/codeblitz#40]
**描述你的问题（Describe you question here）**

**Comment by hacke2** [comment]
gitee 支持的，可以访问这个地址体验 https://codeblitz.cloud.alipay.com/gitee/opensumi/codeblitz，具体代码还在内部，要同步一下 @AhkunTa

**Comment by DengJianShen** [comment]
> gitee 支持的，可以访问这个地址体验 [https://codeblitz.cloud.alipay.com/gitee/opensumi/codeblitz，具体代码还在内部，要同步一下](https://codeblitz.cloud.alipay.com/gitee/opensumi/codeblitz%EF%BC%8C%E5%85%B7%E4%BD%93%E4%BB%A3%E7%A0%81%E8%BF%98%E5%9C%A8%E5%86%85%E9%83%A8%EF%BC%8C%E8%A6%81%E5%90%8C%E6%AD%A5%E4%B8%80%E4%B8%8B) @AhkunTa

@hacke2 你好，请问代码同步了吗

**Comment by AhkunTa** [comment]
#42
