### ISSUE TITLE
[BUG] import { ChatReadableStream } from '@codeblitzjs/ide-sumi-core/lib/server/ai-native/ai-back-service';

### ISSUE THREAD

**Issue by Hj419522039** [opensumi/codeblitz#95]
**描述你的问题（Describe the bug）**
Cannot find module '@codeblitzjs/ide-sumi-core/lib/server/ai-native/ai-back-service' or its corresponding type declarations.
    45 |   sleep,
    46 | } from '@codeblitzjs/ide-core/lib/modules/opensumi__ide-core-browser';
  > 47 | import { ChatReadableStream } from '@codeblitzjs/ide-sumi-core/lib/server/ai-native/ai-back-service';

**复现路径（To Reproduce）**
yarn 
yarn run init
<img width="957" alt="image" src="https://github.com/opensumi/codeblitz/assets/44163217/30c2e034-965e-453b-ab9b-1e87512693d0">

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1]
- Browser:chrome
- Codeblitz Version: [e.g. 1.0.0]

**Comment by bytemain** [comment]
主分支已经修复这个问题，再试一下
